#!/bin/bash

# $1 is program file
# $2 is input file
# $3 is program output file
# $4 is expected output file

program=$1
name=${program%.*}

if [[ $1 == *.cpp ]]
then
    g++ $1 -o $name.out
    if [[ ! -e $name.out ]]
    then
        g++ $1 &> $name.out
        cat $name.out
    fi
    cat $2 | ./$name.out > $3
elif [[ $1 == *.java ]]
then
    javac $1
    if [[ ! -e $name.class ]]
    then
        javac $1 &> $name.class
        cat $name.class
    fi
    cat $2 | java $name > $3
elif [[ $1 == *.py ]]
then
    cat $2 | python $1 > $3
else
    cat $1 > $3
fi
if ! diff --ignore-all-space $3 $4 > /dev/null
then
    echo 'wrong output!'
fi
