#!/bin/bash

# $1 is program file
# $2 is input file
# $3 is program output file
# $4 is expected output file

program=$1
name=${program%.*}

if [[ $1 == *.cpp ]]
then
    g++ $1 -o $name.out
    if [[ $? -ne 0 ]]
    then
        echo 'Compilation error'
        exit
    fi
    cat $2 | ./$name.out > $3
    if [[ $? -ne 0 ]]
    then
        echo 'Runtime error'
        exit
    fi
elif [[ $1 == *.java ]]
then
    cat $1 > Main.java
    javac Main.java
    if [[ $? -ne 0 ]]
    then
        echo 'Compilation error'
        exit
    fi
    cat $2 | java Main > $3
    if [[ $? -ne 0 ]]
    then
        echo 'Runtime error'
        exit
    fi
elif [[ $1 == *.py ]]
then
    cat $2 | python $1 > $3
    if [[ $? -ne 0 ]]
    then
        echo 'Syntax/Runtime error'
        exit
    fi
else
    cat $1 > $3
fi
if ! diff --ignore-all-space $3 $4 > /dev/null
then
    echo 'Wrong output!'
fi
